baseURL = "https://owenbrooks.github.io/"
languageCode = "en-au"
title = "Owen Brooks"
theme = "minimal"
googleAnalytics = ""

[params]
    author = "Owen Brooks"
    description = "Personal blog"
    githubUsername = "#owenbrooks"
    accent = "darkturquoise"
    showBorder = true
    backgroundColor = "white"
    font = "Railway" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "solarized-dark"
    highlightLanguages = ["rust", "python", "c"]

[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

[[menu.main]]
    url = "/about/"
    name = "About"
    weight = 2

[[menu.main]]
    url = "/post/"
    name = "Posts"
    weight = 3

# Social icons to be shown on the right-hand side of the navigation bar.
# The "name" field should match the name of the icon in Font Awesome.
# The list of available icons can be found at http://fontawesome.io/icons.

[[menu.icon]]
    url = "mailto:owen.h.brooks@gmail.com"
    name = "fas fa-envelope"
    weight = 1

[[menu.icon]]
    url = "https://github.com/owenbrooks/"
    name = "fab fa-github"
    weight = 2

[[menu.icon]]
    url = "https://www.linkedin.com/in/owen-brooks-370290184/"
    name = "fab fa-linkedin"
    weight = 4
