title = "Blog"
description = "A blog"
# The URL the site will be built for
base_url = "https://owenbrooks.github.io"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

taxonomies = [
  { name = "categories", feed = true },
  { name = "tags", feed = true },
]


# theme = "zola-bearblog"
# theme = "duckquill"
theme = "terminimal"

[translations]
no_posts = "No posts yet"
remove_filter = "Remove filter"
filtering_for = "Filtering for"
made_with = "Made with"
table_of_contents = "Table of contents"
language = "language"
site = "site"


[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

[extra]
show_only_description = true
enable_post_view_navigation = false
# Put all your custom variables here
date_format = "%Y-%m-%d"
webserver_sends_csp_headers = true

# accent_color = "eb4034"
accent_color = "orange"
logo_text = "Home"
copyright_html = " "

[extra.table_of_contents]
show = true
max_level = 2
visible_on_load = true

[[extra.main_menu]]
name = "Home"
url = "@/_index.md"

[[extra.main_menu]]
name = "Blog"
url = "@/blog/_index.md"
